/* The following code was generated by JFlex 1.4.3 on 21/01/14 01:21 */

package org.kevoree.tools.kevscript.idea.lexer;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static org.kevoree.tools.kevscript.idea.psi.KevScriptTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 21/01/14 01:21 from the specification file
 * <tt>src/org/kevoree/tools/kevscript/idea/lexer/KevScript.flex</tt>
 */
public class KevScriptLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\0\1\1\1\1\22\0\1\1\1\0\1\7"+
    "\4\0\1\5\2\0\1\4\1\0\1\34\2\4\1\3\12\4\1\33"+
    "\1\0\1\36\1\35\1\42\2\0\4\4\1\37\1\41\10\4\1\40"+
    "\13\4\1\0\1\6\2\0\1\4\1\0\1\10\1\17\1\24\1\11"+
    "\1\13\2\4\1\25\1\20\1\4\1\32\1\30\1\14\1\21\1\15"+
    "\1\27\1\4\1\12\1\26\1\23\1\22\1\16\1\31\3\4\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\1\11\4\1\5"+
    "\1\6\1\7\1\1\1\10\1\0\1\11\3\0\13\4"+
    "\1\0\1\12\12\4\1\13\1\0\3\4\1\14\1\15"+
    "\1\16\4\4\1\0\7\4\1\0\1\17\1\20\1\21"+
    "\3\4\1\22\1\0\1\23\1\4\1\24\1\25\1\4"+
    "\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\151\0\214\0\257\0\322\0\365"+
    "\0\u0118\0\u013b\0\u015e\0\u0181\0\u01a4\0\u01c7\0\u01ea\0\u020d"+
    "\0\43\0\43\0\43\0\u0230\0\u0253\0\257\0\43\0\u0276"+
    "\0\322\0\u0299\0\u02bc\0\u02df\0\u0302\0\u0325\0\u0348\0\u036b"+
    "\0\u038e\0\u03b1\0\u03d4\0\u03f7\0\u041a\0\u043d\0\214\0\u0460"+
    "\0\u0483\0\u04a6\0\u04c9\0\u04ec\0\u050f\0\u0532\0\u0555\0\u0578"+
    "\0\u059b\0\214\0\u05be\0\u05e1\0\u0604\0\u0627\0\214\0\214"+
    "\0\214\0\u064a\0\u066d\0\u0690\0\u06b3\0\u06d6\0\u06f9\0\u071c"+
    "\0\u073f\0\u0762\0\u0785\0\u07a8\0\u07cb\0\u07ee\0\214\0\214"+
    "\0\214\0\u0811\0\u0834\0\u0857\0\214\0\u087a\0\214\0\u089d"+
    "\0\214\0\43\0\u08c0\0\214";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int ZZ_TRANS [] = {
    1, 2, 2, 3, 4, 5, 1, 6, 7, 8, 
    9, 4, 10, 4, 4, 11, 12, 13, 14, 4, 
    4, 4, 15, 4, 4, 4, 4, 16, 17, 18, 
    19, 4, 4, 4, 1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, 2, 2, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 20, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, 21, 21, 21, 21, 21, 
    22, 23, 21, 21, 21, 21, 21, 21, 21, 21, 
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
    24, 24, 24, 24, 24, 24, 25, 22, 24, 24, 
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
    24, 24, 24, 24, 24, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 26, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 27, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 28, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 29, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 30, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 31, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 32, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 33, 4, 4, 34, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 35, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 36, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    37, -1, -1, -1, -1, 20, 20, -1, 20, 20, 
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
    21, 21, -1, 21, 21, 21, 21, 21, 21, 21, 
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
    21, 21, 21, 21, 21, 24, 24, -1, 24, 24, 
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 38, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 39, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 40, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 41, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 42, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 43, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 44, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    45, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 46, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 47, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    48, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 49, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, 50, -1, -1, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 51, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 52, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 53, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 54, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 55, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 56, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 57, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 58, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 59, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 60, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, 61, -1, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 62, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    63, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 64, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 65, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 66, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 67, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 68, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, 69, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 70, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 71, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 72, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 73, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 74, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    75, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 76, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, 77, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 78, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 79, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 80, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, 81, -1, -1, -1, -1, 4, 
    -1, -1, -1, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 82, 4, 4, 4, 4, 
    4, 4, -1, -1, -1, -1, 4, 4, 4, -1, 
    -1, -1, -1, -1, 4, -1, -1, -1, 4, 4, 
    4, 83, 4, 4, 4, 4, 4, 4, 4, 4, 
    4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 
    -1, 4, 4, 4, -1, 
  };

  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\3\11\2\1\1\0\1\11\3\0"+
    "\13\1\1\0\14\1\1\0\12\1\1\0\7\1\1\0"+
    "\7\1\1\0\3\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public KevScriptLexer() {
    this((java.io.Reader)null);
  }


  public KevScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public KevScriptLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return INCLUDE;
          }
        case 23: break;
        case 6: 
          { return COMMA;
          }
        case 24: break;
        case 8: 
          { return COMMENT;
          }
        case 25: break;
        case 16: 
          { return DETACH;
          }
        case 26: break;
        case 21: 
          { return EOF;
          }
        case 27: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 28: break;
        case 14: 
          { return BIND;
          }
        case 29: break;
        case 3: 
          { return SUB;
          }
        case 30: break;
        case 12: 
          { return REPO;
          }
        case 31: break;
        case 5: 
          { return COLON;
          }
        case 32: break;
        case 17: 
          { return REMOVE;
          }
        case 33: break;
        case 18: 
          { return UNBIND;
          }
        case 34: break;
        case 11: 
          { return SET;
          }
        case 35: break;
        case 7: 
          { return EQ;
          }
        case 36: break;
        case 22: 
          { return NAMESPACE;
          }
        case 37: break;
        case 13: 
          { return MOVE;
          }
        case 38: break;
        case 15: 
          { return ATTACH;
          }
        case 39: break;
        case 9: 
          { return STRING;
          }
        case 40: break;
        case 4: 
          { return IDENT;
          }
        case 41: break;
        case 10: 
          { return ADD;
          }
        case 42: break;
        case 20: 
          { return NETWORK;
          }
        case 43: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 44: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
