
KevScript ::= +((Statement | Comment eol) ws) ?Comment
Statement ::= Add | Remove | Move | Attach | Detach | Set | AddBinding | DelBinding | Include | Network | AddRepo | Namespace
Add ::= AddToken ws NameList ws ':' ws TypeDef
Remove ::= RemoveToken ws NameList
Move ::= MoveToken ws NameList ws InstancePath
Attach ::= AttachToken ws NameList ws InstancePath
Detach ::= DetachToken ws NameList ws InstancePath
Set ::= SetToken ws InstancePath ?('/' InstancePath) ws '=' ws ['] ws String2 ws :['] | SetToken ws InstancePath ?('/' InstancePath) ws '=' ws ["] ws String2 ws :["]
Network ::= NetworkToken ws InstancePath ws String2
AddBinding ::= BindToken ws InstancePath ws InstancePath
DelBinding ::= UnbindToken ws InstancePath ws InstancePath
AddRepo ::= RepoToken ws RepoString
Include ::= IncludeToken ws String ':' String2
NameList ::= InstancePath ws *(',' ws InstancePath)
TypeDef ::= String ?('/' Version)
Namespace ::= NamespaceToken ws String
InstancePath ::=  (Wildcard | String) *('.' (Wildcard | String))
Wildcard ::= '*'
String ::= +[a-zA-Z0-9_-]
String2::= +[a-zA-Z0-9.:@_-]
Version::= +[a-zA-Z0-9._-]
RepoString::= +(!eol :![ ] .)
Anything::= +(!eol .)
RepoToken ::= 'repo'
IncludeToken ::= 'include'
AddToken ::= 'add'
RemoveToken ::='remove'
MoveToken::='move'
SetToken::='set'
AttachToken::='attach'
DetachToken::='detach'
NetworkToken::='network'
BindToken::='bind'
UnbindToken::='unbind'
NamespaceToken::='namespace'
Comment::='//' Anything
eol::='\r\n' | '\n' | '\r'
ws::= *([ \t] | eol)
