package org.kevoree.kevscript;/*
 * Generated by the Waxeye Parser Generator - version 0.8.0
 * www.waxeye.org
 */

/**
 * The types of AST nodes.
 *
 * @author Waxeye Parser Generator
 */
public enum Type
{
    _Empty,
    _Char,
    _Pos,
    _Neg,
    KevScript,
    Statement,
    Add,
    Remove,
    Move,
    Attach,
    Detach,
    Set,
    Network,
    Dictionary,
    AttrList,
    Attribute,
    AddBinding,
    DelBinding,
    AddRepo,
    Merge,
    NameList,
    Comment,
    RepoToken,
    MergeToken,
    AddToken,
    RemoveToken,
    MoveToken,
    SetToken,
    AttachToken,
    DetachToken,
    NetworkToken,
    BindToken,
    UnbindToken,
    String,
    String2,
    Anything,
    Eol,
    Ws
}
