#!/bin/sh

ssh root@10.0.0.2 "date"
ssh root@10.0.1.1 "date"
ssh root@10.0.2.1 "date"
ssh root@10.0.3.1 "date"
ssh root@10.0.4.1 "date"
ssh root@10.0.5.1 "date"
ssh root@10.0.6.1 "date"
ssh root@10.0.7.1 "date"
ssh root@10.0.8.1 "date"
ssh root@10.0.9.1 "date"
ssh root@10.0.10.1 "date"
