#!/bin/bash

scp $1 root@10.0.0.2:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.1.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.2.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.3.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.4.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.5.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.6.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.7.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.8.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.9.1:/root/kevoree-service/kevoree-service-updater.jar
scp $1 root@10.0.10.1:/root/kevoree-service/kevoree-service-updater.jar
