#!/bin/sh

ssh root@10.0.0.2 reboot
# TODO wait to allow the previous machine to reboot
sleep 120s

ssh root@10.0.1.1 reboot
ssh root@10.0.2.1 reboot
ssh root@10.0.3.1 reboot
ssh root@10.0.4.1 reboot
ssh root@10.0.5.1 reboot
ssh root@10.0.6.1 reboot
ssh root@10.0.7.1 reboot
ssh root@10.0.8.1 reboot
ssh root@10.0.9.1 reboot
ssh root@10.0.10.1 reboot

