<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kevoree.context"
    nsURI="http://kevoree.context/1.0" nsPrefix="org.kevoree.context">
  <eClassifiers xsi:type="ecore:EClass" name="ContextRoot"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" iD="true" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructureReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
