#!/bin/sh

#Settings
APP_PATH="$HOME/kevoree-service" # path where your exec file are
SERVICE="kevoree-runtime"  # name of the exec file without (.jar)
JAVA="/usr/local/bin/java"
SERVICE_UPDATER="kevoree-service-updater"

start() {
	update
  if ps axuw | grep -v grep | grep "$SERVICE.jar" > /dev/null
  then
    echo "Tried to start but $SERVICE was already running!"
  else
    echo "$SERVICE was not running... starting."
    $JAVA -Dnode.log.level=DEBUG -Dnode.name=`hostname` -Dnode.groupType=RestGroup -Xmx1024M -Xms1024M -jar "$APP_PATH/$SERVICE.jar"  > "$APP_PATH/`hostname`.log" &
    sleep 5
    if ps axuw | grep -v grep | grep `hostname` | grep "$SERVICE.jar" > /dev/null
    then
      echo "$SERVICE is now running."
    else
      echo "Could not start $SERVICE."
    fi
  fi
}

stop() {
    if ps axuw | grep -v grep | grep `hostname` | grep "$SERVICE.jar" > /dev/null
    then
        echo "$SERVICE is running... stopping."
		HOSTNAME=`hostname`
        kill `ps axuw | grep -v grep | grep "$HOSTNAME" | grep "$SERVICE.jar" | cut -d' ' -f4`
        sleep 10
		if ps axuw | grep -v grep | grep `hostname` |grep "$SERVICE.jar" > /dev/null
			then
			    echo "$SERVICE could not be shut down... still running."
			else
				echo "$SERVICE is shut down."
			fi
    else
        echo "$SERVICE was not running."
    fi
}

update() {
	java -jar "$APP_PATH/$SERVICE_UPDATER.jar" $APP_PATH/$SERVICE.jar
}

#Start-Stop here
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  update)
    update
    ;;
  status)
    if ps ax | grep -v grep | grep `hostname` | grep "$SERVICE.jar" > /dev/null
    then
      echo "$SERVICE is running."
    else
      echo "$SERVICE is not running."
    fi
    ;;
  *)
  echo "Usage: $SERVICE  {start|stop|status|restart}"
  exit 1
  ;;
esac

exit 0
  
